### ISSUE TITLE
How did you gather the API data?

### ISSUE THREAD

**Issue by DennisTheMenace780** [Danoctum/South-Park-API#19]
Hey from Canada!

I'm messing around with building a REST API in Go, and i'm trying to hash through some ideas regarding what I can use. South Park is one of my favourite shows, so I figured this would be a good API project to build, and i've been familiar with your specific API for some time. 

What I was curious about though is how you ended up getting all of this data without manually entering it? I'd love to try and build something similar just for my own personal project, but the actual collection of the data is not something i'm really sure how you'd go about. So I was just hoping to learn from you (if you're inclined) and see what I can come up with in Go!

**Comment by Danoctum** [comment]
Hi from The Netherlands ;)

Great to see you're using the API, and are building a project with Go!

To scrape the data I've actually built a [HTML scraper](https://github.com/Danoctum/South-Park-API/blob/master/app/Console/Commands/ScrapeDataCommand.php) in the project.
This uses the Symfony Domcrawler to basically just load a HTML page and be able to programmatically walk through the HTML. It works on the southpark.fandom.com domain, which is where all the data is from. The script doesn't work at the moment since the fandom wiki has been updated, but it may be helpful to see how the script goes through the webpages.

In the Go world it seems feasible to do the same with [Colly](https://go-colly.org/)!

At the time I made this there were no API sources for getting this data, so that's why I needed to scrape it from the wiki.

Good luck with your project!
