### ISSUE TITLE
Missing characters

### ISSUE THREAD

**Issue by jeffj6123** [Danoctum/South-Park-API#5]
Some of the episodes having missing character lists which are accounted for in the south park wikis.

**Comment by Danoctum** [comment]
This is due to the character list being quite extensive. 

I'd prefer this API to just have the characters of each episode, and sometimes the wiki references character's alter ego's. This means that for a cartman, you'd have about 10 entries.

Currently the code runs through all of the families to have this filtered out, and will check on each episode if there's a character of a family referenced.

I'm currently not looking to change this as it will create many one-off characters rather than the core characters and families.

**Comment by jeffj6123** [comment]
I mean just for the more "primary characters". I meant for like say episode 200, it currently has no locations or characters listed for it

```
{
  "data": {
    "id": 200,
    "name": "200",
    "season": 14,
    "episode": 5,
    "air_date": "2010-04-14",
    "created_at": "2021-07-14T19:50:58.000000Z",
    "updated_at": "2021-07-14T19:50:58.000000Z",
    "characters": [],
    "locations": []
  }
}
```
I definitely understand wanting to avoid the one off characters and alternative's are also kind of a pain

**Comment by Danoctum** [comment]
I see what you mean. Thanks for the catch.

Episode 200 doesn't have the 'Extra's' tab, which makes it so that the code doesn't register characters.
However, in the script tab there is a list of characters. I think changing from the extra's list to the script list will give a more accurate representation of which characters are in the episode.
