### ISSUE TITLE
thumbnails and episode descriptions

### ISSUE THREAD

**Issue by jeffj6123** [Danoctum/South-Park-API#6]
Hey,

I pulled info from your API to put together my own site and I went a step further of pulling thumbnails and episode descriptions and was wondering if you were interested in this info or adding it yourself.

**Comment by Danoctum** [comment]
Hi Jeff!

Thanks for using this API, it's really cool to see someone using it for their own project! Do you mind sharing a link to the website you're creating? I'm curious to see what you made!

As for the thumbnails and episode descriptions, I can add descriptions. Thumbnails I could add, but that'd be a reference to the Wiki rather than an actual download. Would this suit your need?

**Comment by jeffj6123** [comment]
Hey,

Yes totally, it is a work in progress at the moment and the code will be available but I havent done that yet given I need to scrub out credentials properly for oauth but here is the link and by all means check it out. 

https://southpark-tier.ue.r.appspot.com/

**Comment by jeffj6123** [comment]
Also if you could add a link to the wiki aswell for episodes/characters that would be pretty helpful. I would say the image urls are not necessary per say. I would say with a link to the wiki it becomes pretty simple to pull them and download them locally using a script(thats what I do now but I have to work back the episode URL from what you have as the episode name which can be a bit tricky with slight name differences or encoding)

**Comment by Danoctum** [comment]
Looks like a very cool website! Thanks for making use of the API for your project. Do you mind if I use it once it's done? We've got some fans here at work as well, so would be cool to share the most liked episodes.

Could you specify what's tricky about the differences in encoding? As far as I see the wiki has the characters / episode title as the URL with underscores, which shouldn't be tricky to retrieve.

**Comment by jeffj6123** [comment]
Yes absolutely, id say its usable now but its missing some data. I need to go through and add some missing thumbnails and descriptions. 

I wouldnt say there was too much of an issue, more there wasnt a 1 to 1 mapping with episode names ->  url names which included hashtags and id need to see which other characters, I do think the imagination land episodes were another set that had this issue. These were very ad hoc scripts for pulling images/descriptions.

**Comment by Danoctum** [comment]
Hi Jeff, I've created a branch for adding this data. This will add episode thumbnail URL's and episode descriptions.

I've referenced the biggest image, which can be downscaled on the device if necessary. If you'd need a smaller image because of loading speed reasons then I'd recommend retrieving it another way. 

I'll add a wiki_url in a moment.

**Comment by Danoctum** [comment]
FYI: the API has been updated with some more fields. Take a look! I hope it looks good.

**Comment by jeffj6123** [comment]
@Danoctum testing from your site, it looks great! thanks a ton of for this, it definitely makes it easier not having to rescrape(in a much more brittle)  information you are able to grab pretty easily.

 I will get this reflected into my own site(I hit your API once for the info then cache it all) and if you do notice anything off with my site for the meantime, you could message me on discord warthy#0471

But by all means start making your own tier lists!
